#!/usr/bin/env bash
set -euo pipefail

export HOME=/data
export HERMES_HOME="${HOME}/.hermes"
export HERMES_INSTALL_DIR=/opt/hermes
export PATH="${HERMES_INSTALL_DIR}/.venv/bin:${PATH}"

mkdir -p "${HERMES_HOME}" /data/workspace

python3 - <<'PY'
import json
import os
from pathlib import Path


def yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def env_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


options_path = Path("/data/options.json")
options = json.loads(options_path.read_text(encoding="utf-8")) if options_path.exists() else {}

hermes_home = Path(os.environ["HERMES_HOME"])
hermes_home.mkdir(parents=True, exist_ok=True)
install_dir = Path(os.environ["HERMES_INSTALL_DIR"])

messaging_cwd = options.get("messaging_cwd") or "/data/workspace"
Path(messaging_cwd).mkdir(parents=True, exist_ok=True)

for dirname in ("cron", "sessions", "logs", "hooks", "memories", "skills", "skins", "plans", "workspace", "home"):
    (hermes_home / dirname).mkdir(parents=True, exist_ok=True)

for source_name, target_name in ((".env.example", ".env"), ("cli-config.yaml.example", "config.yaml")):
    source = install_dir / source_name
    target = hermes_home / target_name
    if source.exists() and not target.exists():
        target.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")

soul_source = install_dir / "docker" / "SOUL.md"
soul_target = hermes_home / "SOUL.md"
if soul_source.exists() and not soul_target.exists():
    soul_target.write_text(soul_source.read_text(encoding="utf-8"), encoding="utf-8")

env_lines = [
    "# Generated by the Home Assistant add-on wrapper.",
    "HASS_URL=http://supervisor/core",
    f'SUPERVISOR_TOKEN={env_quote(os.environ.get("SUPERVISOR_TOKEN", ""))}',
    f'HASS_TOKEN={env_quote(os.environ.get("SUPERVISOR_TOKEN", ""))}',
    f"MESSAGING_CWD={env_quote(messaging_cwd)}",
    f'API_SERVER_ENABLED={"true" if options.get("api_server_enabled") else "false"}',
]

for option_key, env_key in (
    ("llm_model", "LLM_MODEL"),
    ("openrouter_api_key", "OPENROUTER_API_KEY"),
    ("openai_base_url", "OPENAI_BASE_URL"),
    ("openai_api_key", "OPENAI_API_KEY"),
    ("api_server_key", "API_SERVER_KEY"),
):
    value = options.get(option_key)
    if value not in (None, ""):
        env_lines.append(f"{env_key}={env_quote(str(value))}")

(hermes_home / ".env").write_text("\n".join(env_lines) + "\n", encoding="utf-8")

watch_domains = options.get("watch_domains") or []
watch_entities = options.get("watch_entities") or []
ignore_entities = options.get("ignore_entities") or []
watch_all = bool(options.get("watch_all", False))
cooldown_seconds = int(options.get("cooldown_seconds", 30))

config_lines = [
    "# Generated by the Home Assistant add-on wrapper.",
    f"model: {yaml_quote(str(options.get('llm_model') or ''))}",
    "platforms:",
    "  homeassistant:",
    "    enabled: true",
    "    extra:",
    f"      watch_all: {'true' if watch_all else 'false'}",
    f"      cooldown_seconds: {cooldown_seconds}",
]

if watch_domains:
    config_lines.append("      watch_domains:")
    for item in watch_domains:
        config_lines.append(f"        - {yaml_quote(str(item))}")
else:
    config_lines.append("      watch_domains: []")

if watch_entities:
    config_lines.append("      watch_entities:")
    for item in watch_entities:
        config_lines.append(f"        - {yaml_quote(str(item))}")
else:
    config_lines.append("      watch_entities: []")

if ignore_entities:
    config_lines.append("      ignore_entities:")
    for item in ignore_entities:
        config_lines.append(f"        - {yaml_quote(str(item))}")
else:
    config_lines.append("      ignore_entities: []")

config_lines.extend(
    [
        "terminal:",
        "  backend: local",
        f"  cwd: {yaml_quote(messaging_cwd)}",
    ]
)

(hermes_home / "config.yaml").write_text("\n".join(config_lines) + "\n", encoding="utf-8")
PY

if [ -d "${HERMES_INSTALL_DIR}/skills" ]; then
  python3 "${HERMES_INSTALL_DIR}/tools/skills_sync.py"
fi

echo "Starting Hermes Agent gateway..."
exec hermes gateway
